org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-all.zip
android.suppressUnsupportedCompileSdk=36
systemProp.http.connectionTimeout=600000
systemProp.http.readTimeout=600000
kotlin.jvm.target.validation.mode = IGNORE
android.overrideSdkCheck=true 
RELEASE_STORE_FILE=keystore/my-release-key.jks
RELEASE_STORE_PASSWORD=CHIjenny@1991
RELEASE_KEY_ALIAS=my-key-alias
RELEASE_KEY_PASSWORD=CHIjenny@1991
org.gradle.daemon=true
org.gradle.parallel=true 
# Force 16KB page size support and uncompressed native libraries
 
android.enableR8.fullMode=true
